# This workflow will run tests using node and then publish a frontend browser-based package to NPM when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Loggify-lite

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/setup-node@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Clean install dependencies
        run: npm ci 

      - name: Test the code
        run: npm run test

      - name: Build browser package
        run: npm run build

      - name: Check if version is already published
        id: check_version
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          PACKAGE_VERSION=$(jq -r .version package.json)
          NPM_VERSIONS=$(npm view "$PACKAGE_NAME" versions --json || echo "[]")
          
          if echo "$NPM_VERSIONS" | jq -e ". | index(\"$PACKAGE_VERSION\")" >/dev/null; then
            echo "Version $PACKAGE_VERSION is already published."
            echo "skip_publish=true" >> $GITHUB_ENV
          else
            echo "Publishing version $PACKAGE_VERSION..."
            echo "skip_publish=false" >> $GITHUB_ENV
          fi

      - name: Check bundle size
        run: |
          ls -lh dist/
          gzip -9 < dist/index.js | wc -c

      - name: Publish to npm
        if: env.skip_publish == 'false'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
      - name: Success message
        if: env.skip_publish == 'false'
        run: echo "✅ Package published successfully!"
